version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: back/dockerfile
    volumes:
      # プロジェクトのルート全体を /workspaces/プロジェクト名 にマウント
      - ../..:/workspaces/${localWorkspaceFolderBasename}:cached
    networks:
      - amadeus-net
    environment:
      - OLLAMA_HOST=http://ollama:11434

  frontend:
    build:
      context: ../..
      dockerfile: front/dockerfile
    volumes:
      - ../../front:/app:cached
      # コンテナ内の node_modules をホスト側のマウントで上書きしないように保護する
      - /app/node_modules
    ports:
      - "5173:5173"
      - "8000:8000"
    networks:
      - amadeus-net
    # フロントエンドコンテナも立ち上げっぱなしにする
    tty: true

  ollama:
    # (前回と同じ設定)
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - amadeus-net

networks:
  amadeus-net:

volumes:
  ollama_data: